### ISSUE TITLE
Questions for 16bits/24bits resolution, and also the 5ms frame

### ISSUE THREAD

**Issue by rick1082** [google/liblc3#57]
Thanks so much for the great implementation for LC3/LC3plus!
Excuse me to ask couple questions in here:
1. For LC3/LC3plus, we do see the input signal will be scaled to the range of [−32,768, 32,768]. Which means if the input data is using 24 bits width, there's a chance the value will be clamped. Would this mean the distortion should be expected when using LC3/LC3plus to handle 24 bits data? And would it also means there would be no difference to use 16/24bits as input data since value out of range will be calmped. Or could LC3 or LC3plus in HR mode can do compensation for mimic the lost value out of 16bits?

2. For using 5ms frame input, would it necessary to enable the HR mode? Or using ordinary mode should be OK.
Since I try to using the latest release version of liblc3 on Zephyr with nRF5340 from NordicSemi, and the quality for 5ms frame is not working properly but 10ms works perfact! Not sure if there's something I missed.

Any comments would be very appreciated.

**Comment by asoulier** [comment]
1. Are you pointing the [load function](https://github.com/google/liblc3/blob/main/src/lc3.c#L224) or siblings? The signal in `xt` is always on 16 bits, but never used as signal to be encoded. It's only used for pitch detection in LTPF, and allow faster fixed point processing on 16 bits, this bit depth is enough for this.
Internally the encoded/decoded signal is stored in floating point, scaled in the range [-32768.0;32768.0] (instead of the scaling used by the interface [-1.0;1.0]. This is floating point, you'll have prevision after the dot.
The spectrum coefficients are clamped between [-32768;32768] for non HR mode. Note that this is very different of the input PCM scaling. Before that, the signal is scaled to fulfill this range (scaling factors), and this is spectrum coefficient (not temporal samples).  

2. Using ordinary mode should be OK, HR mode add precision but not compression efficiency. Reducing the frame duration, add constraints to the encoder, you should increase the bit rate to have comparable audio quality. (thumb of rule, increase the bit rate by 25% to have comparable audio quality when reducing frame duration by half). Do you have a drop of audio quality or something completely broken?

**Comment by rick1082** [comment]
Hello @asoulier,
Thanks for the great info, I will take a further study on first part.
For second part, I tested with 48KHz sampling rate with 16 bits depth, 5ms audio frame duration and 96kbps bitrate, but the stream after enc/dec distorted a lot, I can tell the rhythm, but with lots of nosie and seems some of frequency band are lost. But 10ms audio frame with same setting works nicely. I will continue check if there's something wrong from my test application, or something wrong with porting.

**Comment by rick1082** [comment]
Confirmed that 5ms can work in ordinary mode, we don't need to set HR mode for it. And thanks for the great comment and great LC3/LC3plus implementation.
